### ISSUE TITLE
Long site name overflows title area.

### ISSUE THREAD

**Issue by teletha** [WhitePaper233/yukina#3]
It would be great if you could remove the fixed length width of the title class.

![{C3D53548-E9CA-48EB-A43A-7BB91DB1A2F6}](https://github.com/user-attachments/assets/d9b87f12-9389-4a28-bbee-364605c614b9)

**Comment by WhitePaper233** [comment]
Fixed and optimized display in https://github.com/WhitePaper233/yukina/commit/53b71259e976c337d316316b7787bcb9ba6a39ad.
Sorry for the wrong issue id in the commit info :/.
![optimzation result](https://github.com/user-attachments/assets/1583cc99-4925-41b3-b468-e7ba56ea01b4)

**Comment by WhitePaper233** [comment]
I intend to separate the navbar brand title and the banner title into two options in future updates. However, for now, I’ll leave it as is because I don’t have much time to maintain the project over the next two weeks.

**Comment by teletha** [comment]
Thank you for your prompt response.

**Comment by WhitePaper233** [comment]
I have created a new commit for further fix and optimzation of responsive layout issues, also I decoupled brand title and banner title settings. Please check it out in https://github.com/WhitePaper233/yukina/commit/6f47141a9299d4c64ace62e39dea4d3a01c4b89c
